### ISSUE TITLE
Upgrade to 16.04 ?

### ISSUE THREAD

**Issue by nondidju** [nthchild/ubuntu-ac100#1]
Hello,

This website contains the most recent news about the ac100. It's good to meet people who still cares about this computer. :)

Aye you tried to upgrade to ubuntu 16.04 ? When I try to upgrade the kernel up to 3.15, I get an error from initramfs about the tail of the boot image on /dev/mmcblk0p2.

I would be very intersted to know how to maintain this computer up to date.

**Comment by nthchild** [comment]
Hey,

I'm waiting for 16.04.2 release, to make sure all annoying bugs are fixed. However I can't promise anything.

First of all, `libc6` recommends 3.2+ kernel, so we need to switch to U-boot. I've successfully booted upstream 3.16.39 kernel and Xubuntu Core, but it's really unstable and some basic features such as sound don't work. Sometimes kernel can't boot at all. Secondly, this device has only 512MB of RAM, therefore we need to switch to XFCE, which requires extra configuration (and Thunar bugfixes...).

**Comment by nthchild** [comment]
Experimental Xubuntu 16.04 is out, can be found here: <https://github.com/nthchild/ubuntu-ac100-xenial>
